### ISSUE TITLE
Add a Split Helper

### ISSUE THREAD

**Issue by gespi1** [checkly/handlebars#93]
Looking to process checkly tags, since tags is list rather than a dictionary/map. We are creating tags in the format of `key:pair` and need a way to get a value based off a key to use. We do this because we want to use a single webhook AC to send to statuspage but each endpoint has its own component id and needs to be passed as a part of the URL. Thus we are storing component id's as tags, e.g. `component_id:12345`.

Adding a Split func can do just that.

I created a branch but cannot push and create a PR. So here is the code.

```
handlebars.registerHelper('$SPLIT', () => function(string, splitter, index) {
    if (index == -1) {
      return string.split(splitter);
    }
    return string.split(splitter)[index];
  })
```

README
```
### {{$SPLIT}}
Returns an array of split strings or an element from a the array based off the `index` value. 

\```handlebars
: {{$SPLIT "this is a string", " ", -1 }}
<!-- results in: '["this", "is", "a", "string"]' -->
\```

\```handlebars
: {{$SPLIT "this is another string", " ", 2}}
<!-- results in: 'another' -->
\```

```

**Comment by ianaya89** [comment]
@gespi1 thanks for your contribution, we will take a look and get back soon!

**Comment by gespi1** [comment]
Ty for your speedy reply

**Comment by gespi-consensys** [comment]
any update? @ianaya89

**Comment by ianaya89** [comment]
Sorry for the delay here, it is on the radar. Will tackle it soon!

**Comment by gespi-consensys** [comment]
@tnolet ty. going to test it out :)

**Comment by tnolet** [comment]
> @tnolet ty. going to test it out :) 

Hi, this is not line yet. We will pick that up tomorrow

**Comment by tnolet** [comment]
@gespi-consensys this is now live and usable from our Webhooks alert channel. I tested it with the following example:
Note that you need to turn the `TAGS` string into an array first. Then you can split the individual tags based on a separator. In my example, I added a tag called `team:product` and it render this to `"tags" : ["product"]`
```
{
  "event": "{{ALERT_TITLE}}",
  "link": "{{RESULT_LINK}}", 
  "tags": [{{#each TAGS}} "{{split this ':' 1}}" {{#unless @last}},{{/unless}} {{/each}}]
  }
```

**Comment by ghost** [comment]
Thanks @tnolet! Works like a charm. Used it with the `#has` helper as well
```
{{#each TAGS}}{{#has this "key"}}{{split this ':' 1}}{{/has}}{{/each}}
```

**Comment by tnolet** [comment]
Excellent. Happy to help.
